### ISSUE TITLE
Self uploaded videos under com.hteumeuleu.playorama don't appear in player

### ISSUE THREAD

**Issue by Pcenginefx** [hteumeuleu/playorama#1]
Hi - I followed step 1.3 on adding my own pdv/wav to my Playdate under the data/com.hteumeuleu.playorama folder and it doesn't show up at all inside of the app - it only shows the sample video under assets.

**Comment by hteumeuleu** [comment]
Hi - Thanks for your report. This may happen if the app fails to open either the audio or pdv file. My guess is this is more likely coming from the audio file. I know I've add trouble with some files (and am still unsure why). Try to reencode your wav file with a different software. (I know I had better luck with Audacity than with ffmpeg.) If this doesn't make it, feel free to send a link to your audio and video files.

**Comment by Pcenginefx** [comment]
Ahh ok - yeah I'm currently still messing with the encoder so will let you know. I'm actually using Adobe Premiere to format my video/audio for the encoder.

**Comment by Pcenginefx** [comment]
Ok I tried all sorts of ways to convert the audio file and the video still didn't show up in the player. Tried using Adobe Premiere and Audacity as a .wav using IMA ADPCM as per the SDK instructions but still no luck. I've attached my video for you to have a look at
[TronLegacy.zip](https://github.com/hteumeuleu/playorama/files/8888789/TronLegacy.zip)
.

**Comment by hteumeuleu** [comment]
If you have the SDK, you can replace the sample files in the actual app (in the `assets` folder), or edit/duplicate the lines 165-170 in `Menu.lua` to add your own video. https://github.com/hteumeuleu/playorama/blob/main/Source/Menu.lua#L165-L170

I was able to play your Tron video this way.

**Comment by hteumeuleu** [comment]
Hey! Just for the heads up, I've made a new release that will display an error message in case the app fails to open a video. I'm still trying to figure things out, but I'm under the impression it can not open a wav file bigger than 16 MB. I'll continue my debugging on this…

**Comment by Pcenginefx** [comment]
Hiya! Yes I was able to edit Menu.lua manually and add my Tron video and build the player via the SDK so that worked. I should be able to test out the new release here as well - if I encounter any issues, I'll let you know.

**Comment by metaColin** [comment]
Hey, I'm running into the same issue @Pcenginefx described. I successfully followed the encoding steps (I used FFMPEG to get a 2MB .wav)

Is there anything short of editing/recompiling the app I can do to enable playback?

**Comment by Pcenginefx** [comment]
> Hey, I'm running into the same issue @Pcenginefx described. I successfully followed the encoding steps (I used FFMPEG to get a 2MB .wav)
> 
> Is there anything short of editing/recompiling the app I can do to enable playback?

Heya @metaColin - unless hteumeuleu has an update since we last talked, we've not been able to get a video to show up in the player unless you hard-code the video into the Menu.lua as previously instructed. There is a new version of the player out (not sure if you tried it yet) but we're still figuring it out....

**Comment by hteumeuleu** [comment]
One thing I just learnt yesterday is that the Playdate can only play `pda`, not `wav`. From Panic’s [Dave Hayden](https://devforum.play.date/t/im-been-having-a-lot-of-trouble-with-the-fileplayer/6489/4) himself:

> Unfortunately, we don't support WAV playback directly. The compiler converts WAV files to .pda format which is similar but slightly different.

This is it works when including them in the app. (Because the compiler converts WAVs to PDA.) So I need to rework a few things:

1. Support video even if the audio fails to open. 
2. Support MP3 audio format (this will disallow the crank’s fast backward due to the API not allowing negative playback rates for mp3s).
3. I'm finding that audio encoding as a WAV in IMA ADPCM fails to play backward. (That's the case with your Tron video, @Pcenginefx.)

I'd also like to dig into PDA and PDV file formats to see if I could build an encoder, because right now the process is pretty hard to get your own video in the right format. So this is still far from prime time. But it’s nice to see people enjoy this from [this Reddit's post](https://www.reddit.com/r/PlaydateConsole/comments/vlol7j/tron_legacy_clip_running_on_my_playdate/)!

**Comment by hteumeuleu** [comment]
Hey there! Just released [v1.0.0-beta.3](https://github.com/hteumeuleu/playorama/releases/tag/v1.0.0-beta.3) that fixes the first point above. Need to look into 2 and 3 now.

**Comment by hteumeuleu** [comment]
I just released [v1.0.0-beta.4](https://github.com/hteumeuleu/playorama/releases/tag/v1.0.0-beta.4) that fixes points 2 and 3 above. Let me know if you've got any other feedback. I'll close the thread otherwise.

**Comment by Pcenginefx** [comment]
Awesome! Thanks for working on it - I'll see if I can try out the new beta here shortly.
